title: Transmutation Engine
description: Project Documentation
baseurl: "/TransmutationEngine"
url: "https://subunits.github.io"

# This switches you to a high-quality dark professional theme
remote_theme: jasonlong/cayman-theme

# Plugins needed to make remote themes work
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Force Jekyll to clean the old files
keep_files: [".git", ".svn"]
